# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 218)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_number = QtWidgets.QFrame(self.centralwidget)
        self.frame_number.setStyleSheet("QFrame {\n"
"    background:rgb(245, 245, 245);\n"
"}")
        self.frame_number.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_number.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_number.setObjectName("frame_number")
        self.groupBox = QtWidgets.QGroupBox(self.frame_number)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 141))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 20, 341, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black;\n"
"font-size: 89px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_number)
        self.frame_tools = QtWidgets.QFrame(self.centralwidget)
        self.frame_tools.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_tools.setStyleSheet("")
        self.frame_tools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tools.setObjectName("frame_tools")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_tools)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_start = QtWidgets.QPushButton(self.frame_tools)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"           background-color: #4CAF50;\n"
"           border: none;\n"
"           color: white;\n"
"           padding: 10px 32px;\n"
"           text-align: center;\n"
"           text-decoration: none;\n"
"          display: inline-block;\n"
"           font-size: 18px;\n"
"          margin: 4px 2px;\n"
"           cursor: pointer;\n"
"           border-radius: 10px;   \n"
"min-height: 20px                }\n"
"QPushButton:hover {\n"
"          background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n "
"          background-color: #388E3C; \n"
"}")  # Click effect
                       
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.frame_tools)
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
"     background-color: #f44336;\n"
"     border: none;\n"
"     color: white;\n"
"     padding: 10px 32px;\n"
"     text-align: center;\n"
"     text-decoration: none;\n"
"     display: inline-block;\n"
"     font-size: 16px; \n"
"     margin: 4px 2px;\n"
"     cursor:    pointer;\n"
"     border-radius:    10px;\n"
"min-height: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"                 background-color: #d32f2f;\n"
"                 }")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.pushButton_set = QtWidgets.QPushButton(self.frame_tools)
        self.pushButton_set.setStyleSheet("QPushButton {\n"
"                                background-color: #2196F3;\n"
"                                border: none;\n"
"                                color: white;\n"
"                                padding: 10px 32px; \n"
"                                text-align: center;\n"
"                                text-decoration: none;\n"
"                                display: inline-block;\n"
"                                font-size: 16px;\n"
"                                margin: 4px 2px;\n"
"                                cursor: pointer;\n"
"                                border-radius: 10px;\n"
"                                min-height: 20px; \n"
"                                }\n"
"                                QPushButton:hover {\n"
"                                background-color: #1976D2;\n"
"                                }")
        self.pushButton_set.setObjectName("pushButton_set")
        self.horizontalLayout.addWidget(self.pushButton_set)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_tools)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "25:00"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_stop.setText(_translate("MainWindow", "停止"))
        self.pushButton_set.setText(_translate("MainWindow", "设置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
